learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
   	path(r'users/',include(('users.urls', 'users'), namespace='users')),
]

learning_logs/urls.py
"""URL schemes for Learning_Logs"""
from django.conf.urls import url, include

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^topics/$', views.topics, name = 'topics'),
	url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name ='topic'),
	url(r'^new_topic/$', views.new_topic, name='new_topic'),
	url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
	url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
 
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
	url(r'^logout/$', views.logout_view, name='logout'),
	url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.db import models 
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
	text = models.CharField(max_length = 200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User,on_delete=models.CASCADE)
	def __str__(self):
		return self.text

class Entry(models.Model):
	"""user's info about the theme"""
	topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entires'

	def __str__(self):
		"""returns str view of the model"""
		return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text':''}

class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labesl = {'text':''}
		widgets = {'text':forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from .models import Topic,Entry
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
	"""creating learning log app homepage"""
	return render(request,'index.html')

@login_required
def topics(request):
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {'topics': topics}
	return render(request, 'topics.html', context)

@login_required
def topic(request,topic_id):
	topic = Topic.objects.get(id=topic_id)
	if topic.owner != request.user:
		raise Http404
	entries = topic.entry_set.order_by('-date_added')
	context = {'topic': topic, 'entries' : entries}
	return render(request, 'topic.html', context)

@login_required
def new_topic(request):
	if request.method != 'POST':
		form = TopicForm()
	else:
		form = TopicForm(data=request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))
	context = {'form' : form}
	return render(request, 'new_topic.html', context)

@login_required
def new_entry(request,topic_id):
	topic = Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		form = EntryForm()
	else:
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
	context = {'topic' : topic,'form' : form}
	return render(request, 'new_entry.html', context)

@login_required
def edit_entry(request,entry_id):
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic
	if topic.owner != request.user:
		raise Http404
	if request.method != 'POST':
		form = EntryForm(instance=entry)
	else:
		form = EntryForm(instance=entry,data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic', args =[topic.id]))
	context = {'entry' : entry, 'topic' : topic, 'form' : form}
	return render(request, 'edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
	if request.method != 'POST':
		form = UserCreationForm()
	else:
		form = UserCreationForm(data=request.POST)

	if form.is_valid():
		new_user = form.save()
		authentificated_user = authenticate(username=new_user.username, password=request.POST['password1'])
		login(request,authentificated_user)
		return HttpResponseRedirect(reverse('learning_logs:index'))
	context = {'form' : form}
	return render(request, 'register.html', context)

learning_logs/templates/base.html
<p>
	<a href="{%url 'learning_logs:index' %}">Learning Log</a> -
	<a href="{%url 'learning_logs:topics' %}">Topics</a> - 
	{% if user.is_authenticated %}
		Hello, {{ user.username }}.
		<a href="{% url 'users:logout' %}">Log out</a>
	{% else %}
		<a href="{% url 'users:register' %}">Register</a>
		<a href=" {% url 'users:login' %}">Log in</a>
	{% endif %}
</p>
{%block content %}{% endblock content%}

learning_logs/templates/edit_entry.html
{% extends 'base.html'%}

{%block content%}

	<p><a href=" {% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>

	<p>Edit entry:</p>

	<form action="{%url 'learning_logs:edit_entry' entry.id %}" method="post">
		{% csrf_token %}
		{{form.as_p }}
		<button name="submit">save changes</button>
	</form>

{% endblock content%}

learning_logs/templates/index.html
{% extends "base.html" %}

{%block content %}
<p>Learning Log<p>
<p>Learning Log helps you keep track of your learning, for any topic you're learning about.<p>
{%endblock content%}

learning_logs/templates/new_entry.html
{% extends 'base.html' %}
{% block content %}

<p><a href="{%url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
	{% csrf_token %}
	{{ form.as_p }}
	<button name='submit'>add entry</button>
</form>

{% endblock content %}

learning_logs/templates/new_topic.html
{% extends 'base.html' %}
{% block content %}
	<p>Add a new topic:</p>
	<form action="{% url 'learning_logs:new_topic' %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">add toppic</button>
	</form>

{% endblock content %}

learning_logs/templates/templates/topics.html
{% extends "base.html" %}

{%block content %}

	<p>Topics</p>

	<ul>
		{% for topic in topics %}
			<li>{{topic}}</li>
		{%empty%}
			<li> No topics have been added yet</li>
		{%endfor%}
	</ul>

{%endblock content%}

learning_logs/templates/topic.html
{%extends 'base.html' %}

{%block content%}

<p>Topic: {{topic}}</p>

<p>Entries:</p>
<p>
	<a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
<ul>
	{% for entry in entries %}
	<li>
		<p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
		<p>{{ entry.text|linebreaks }}</p>
		<p>
			<a href="{%url 'learning_logs:edit_entry' entry.id %}"> edit entry</a>
		</p>
	</li>
{%empty%}
	<li>
		There are no entries for this topic yet.
	</li>
{%endfor%}
</ul>

{%endblock content%}

learning_logs/templates/topics.html
{% extends "base.html" %}

{%block content %}

	<p>Topics</p>

	<ul>
		{% for topic in topics %}
			<li>
				<a href="{%url 'learning_logs:topic' topic.id %}">{{topic}}</a>
			</li>
		{%empty%}
			<li> No topics have been added yet</li>
		{%endfor%}
	</ul>
	<a href="{% url 'learning_logs:new_topic'%}"> Add a new topic:</a>

{%endblock content%}

users/templates/login.html
{% extends 'base.html' %}
{% block content %}
	{% if form.errors %}
	<p> Your username and password didn't match. Please try again.</p>
	{% endif%}

	<form method="post" action="{% url 'users:login' %}">
	{% csrf_token %}
	{{ form.as_p }}

	<button name="submit"> Log in</button>
	<input type="hidden" name ="next" value="{% url 'learning_logs:index' %}"/>
	</form>
{% endblock content%}

users/templates/register.html
{% extends 'base.html' %}
{% block content %}
	<form method="post" action="{% url 'users:register' %}">
	{% csrf_token %}
	{{ form.as_p }}

	<button name="submit"> Register</button>
	<input type="hidden" name ="next" value="{% url 'learning_logs:index' %}"/>
	</form>
{% endblock content%}